### PR TITLE
TC001

### PR DESCRIPTION
**Pull request by EdisonKashari**
TC001 is done please review and merged

### CODE REVIEW

**Comment by EdisonKashari** [comment]
is the code correct?

**Comment by Farangez** [comment]
It showed that branch is Merged successful. Should I delete the branch?

**Comment by EdisonKashari** [comment]
he said delete after merge

**Comment by EdisonKashari** [comment]
ok great job,seee you later

**Comment by Farangez** [comment]
So every time we have to create new branch?

**Comment by Farangez** [comment]
So every time we have to create new branch?

**Comment by EdisonKashari** [comment]
if we have a new features i think

**Pull request merged**
